# AR parameters such as FFT parameters.
audio_repr: ar_esresnext_fbsp.AR_ESResNeXtFBSP
feature_d: 2048
sample_rate: 44100
# temporal_pooling_type: -> not using common temporal pooling.

# Training parameters.
batch_size: 64
lr_lineareval: 0.0003
# not ready lr_finetune_frozen: 0.00003
# not ready lr_finetune_finetune: 0.00003
report_per_epochs: 20
early_stop_epochs: 20
