# AR parameters such as FFT parameters.
audio_repr: ar_wav2vec2.AR_Wav2Vec2Logit
feature_d: 32
sample_rate: 16000
temporal_pooling_type: mean_max

# Training parameters.
batch_size: 256
lr_lineareval: 0.0003
# not ready lr_finetune_frozen: 0.0001
# not ready lr_finetune_finetune: 0.0001
report_per_epochs: 20
early_stop_epochs: 20

# Model specific parameters.
wav2vec_model: facebook/wav2vec2-large-960h-lv60
